name: Run CDP Tests on BrowserStack

on:
  workflow_dispatch:

jobs:
  test:
    name: CDP Tests on Desktop and iPhone 14
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run CDP test on Desktop Chrome via BrowserStack
        run: npx ts-node tests/computrition.spec.ts

      - name: Run CDP test on iPhone 14 via BrowserStack
        run: npx ts-node tests/computrition.spec.ts
        env:
          BROWSERSTACK_DEVICE: 'iPhone 14'
