name: Run Playwright Tests on Desktop and iPhone

on:
  workflow_dispatch:

jobs:
  test:
    name: Playwright Tests on Desktop and iPhone
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (desktop + iPhone)
        run: npx playwright test --project=desktop-chrome --project=iphone-14
