name: Run Playwright Tests via BrowserStack Automate

on:
  workflow_dispatch:

jobs:
  test:
    name: Playwright Tests on BrowserStack Automate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests via BrowserStack Automate
        run: npx browserstack-playwright --config browserstack.config.json
